version: '3.8'

services:
  locket-vip:
    build: .
    container_name: locket-vip-server
    restart: always
    ports:
      # Đổi cổng sang 3030 để không bị trùng với ứng dụng Remotion đang chạy cổng 3000 trên Ubuntu
      - "3030:3000"
    volumes:
      - ./vip_users.json:/app/vip_users.json
    environment:
      - NODE_ENV=production
      - PORT=3000
